# Generated by Django 2.1.7 on 2019-05-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together={('user', 'project')},
        ),
    ]
